on: [push]

jobs:
  build:
    name: Build All
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [mark-one]
        boot: [uSD]
    steps:

    - uses: actions/checkout@v1

    - uses: ./.github/actions/docker
      with:
        entrypoint: 'cd /github/workspace && make all V=mark-one IMX=imx53'
